language: generic

sudo: required

dist: trusty

services: docker

script:
  - docker run -v $TRAVIS_BUILD_DIR:/course-inspector lamtev/java:latest /bin/bash -c " cd course-inspector && gradle build "

before_deploy:
  - sudo chmod 777 ${TRAVIS_BUILD_DIR}/cli_utility/build/distributions/inspector.zip

deploy:
  provider: releases
  api_key: "$GITHUB_DEPLOY_TOKEN"
  file:
    - ${TRAVIS_BUILD_DIR}/cli_utility/build/distributions/inspector.zip
  skip_cleanup: true
  on:
    tags: true
